
/*
 HTML5 Shiv v3.6.2 | @afarkas @jdalton @jon_neal @rem | MIT/GPL2 Licensed
*/
(function(l,f){function m(){var a=e.elements;return"string"==typeof a?a.split(" "):a}function i(a){var b=n[a[o]];b||(b={},h++,a[o]=h,n[h]=b);return b}function p(a,b,c){b||(b=f);if(g)return b.createElement(a);c||(c=i(b));b=c.cache[a]?c.cache[a].cloneNode():r.test(a)?(c.cache[a]=c.createElem(a)).cloneNode():c.createElem(a);return b.canHaveChildren&&!s.test(a)?c.frag.appendChild(b):b}function t(a,b){if(!b.cache)b.cache={},b.createElem=a.createElement,b.createFrag=a.createDocumentFragment,b.frag=b.createFrag();
a.createElement=function(c){return!e.shivMethods?b.createElem(c):p(c,a,b)};a.createDocumentFragment=Function("h,f","return function(){var n=f.cloneNode(),c=n.createElement;h.shivMethods&&("+m().join().replace(/\w+/g,function(a){b.createElem(a);b.frag.createElement(a);return'c("'+a+'")'})+");return n}")(e,b.frag)}function q(a){a||(a=f);var b=i(a);if(e.shivCSS&&!j&&!b.hasCSS){var c,d=a;c=d.createElement("p");d=d.getElementsByTagName("head")[0]||d.documentElement;c.innerHTML="x<style>article,aside,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}mark{background:#FF0;color:#000}</style>";
c=d.insertBefore(c.lastChild,d.firstChild);b.hasCSS=!!c}g||t(a,b);return a}var k=l.html5||{},s=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i,r=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i,j,o="_html5shiv",h=0,n={},g;(function(){try{var a=f.createElement("a");a.innerHTML="<xyz></xyz>";j="hidden"in a;var b;if(!(b=1==a.childNodes.length)){f.createElement("a");var c=f.createDocumentFragment();b="undefined"==typeof c.cloneNode||
"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}g=b}catch(d){g=j=!0}})();var e={elements:k.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup main mark meter nav output progress section summary time video",version:"3.6.2",shivCSS:!1!==k.shivCSS,supportsUnknownElements:g,shivMethods:!1!==k.shivMethods,type:"default",shivDocument:q,createElement:p,createDocumentFragment:function(a,b){a||(a=f);if(g)return a.createDocumentFragment();
for(var b=b||i(a),c=b.frag.cloneNode(),d=0,e=m(),h=e.length;d<h;d++)c.createElement(e[d]);return c}};l.html5=e;q(f)})(this,document);
@font-face{font-family:'Montserrat';font-style:normal;font-weight:400;src:local('Montserrat-Regular'),url(/fonts/montserrat.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2212,U+2215,U+E0FF,U+EFFD,U+F000;}@font-face{font-family:'Montserrat';font-style:normal;font-weight:700;src:local('Montserrat-Bold'),url(/fonts/montserrat_bold.woff2) format('woff2');unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02C6,U+02DA,U+02DC,U+2000-206F,U+2074,U+20AC,U+2212,U+2215,U+E0FF,U+EFFD,U+F000;}a{text-decoration:none;}html{background:#FFF;font-size:12px;font-family:'Helvetica Neue',Helvetica,'PingFang SC','Microsoft Yahei','WenQuanYi Micro Hei',Arial,Verdana,sans-serif;}h1{text-align:center;font-size:14px;color:#282828;margin:10px 0px;}h2{font-size:12px;text-align:center;margin-top:18px;color:#282828;}img.center{display:block;max-width:500px;margin-left:auto;margin-right:auto;}.slogan{display:block;margin-left:auto;margin-right:auto;margin-top:10px;margin-bottom:50px;font-family:'Montserrat',sans-serif;text-align:center;line-height:24px;color:#666;}p{display:block;margin-left:auto;margin-right:auto;margin-top:10px;margin-bottom:0;font-family:'Montserrat',sans-serif;text-align:center;line-height:24px;color:#666;}.block{width:240px;margin:0 auto 32px;padding:32px 32px 26px;background:#f4f4f4;border-radius:16px;}.block.event{padding:10px 12px 12px;border-radius:8px;width:280px;text-align:center;font-family:'Montserrat',sans-serif;background:#AE5FF2;}.block.event a{text-decoration:none;color:#FFF;}.block.qrcode{background:none;padding-top:10px;padding-bottom:10px;}.smaller{font-size:12px;padding:8px;}header{margin-top:32px;}footer>p{color:#999;margin-bottom:20px;}# YE